# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Madrid Web Dev
subtitle: La página web de Madrid Web Dev para mantenerte informado de lo que ocurre.

# Insert your disqus shortname
#disqus:
#    shortname: