# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Madrid Web Dev
subtitle: Grupo local de desarrollo centrado en la web y el software libre. En está página puedes mantenerte informado de nuestras actividades.

# Insert your disqus shortname
#disqus:
#    shortname:
